# Generated by Django 6.0 on 2026-03-04 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField()),
                ("provider", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "raw_price_snapshots",
                "indexes": [
                    models.Index(
                        fields=["provider", "region", "fetched_at"],
                        name="raw_price_s_provide_242ba1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawEC2Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField()),
                ("credential_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_ec2_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "raw_ec2_snapshots",
                "indexes": [
                    models.Index(
                        fields=["user", "fetched_at"], name="raw_ec2_sna_user_id_4e7f51_idx"
                    )
                ],
            },
        ),
    ]
