# Generated by Django 6.0 on 2026-03-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawec2snapshot",
            name="payload_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="rawpricesnapshot",
            name="payload_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
    ]
