# Generated by Django 6.0 on 2026-03-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raw", "0002_rawec2snapshot_payload_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawAzureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField()),
                ("payload_hash", models.CharField(db_index=True, default="", max_length=64)),
                ("credential_id", models.IntegerField()),
                ("subscription_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_azure_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "raw_azure_snapshots",
                "indexes": [
                    models.Index(
                        fields=["user", "fetched_at"], name="raw_azure_s_user_id_aee358_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawGCPSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField()),
                ("payload_hash", models.CharField(db_index=True, default="", max_length=64)),
                ("credential_id", models.IntegerField()),
                ("project_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_gcp_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "raw_gcp_snapshots",
                "indexes": [
                    models.Index(
                        fields=["user", "fetched_at"], name="raw_gcp_sna_user_id_e62eea_idx"
                    )
                ],
            },
        ),
    ]
