# Generated by Django 6.0 on 2026-03-30 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raw", "0003_rawazuresnapshot_rawgcpsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawazuresnapshot",
            index=models.Index(
                fields=["credential_id", "fetched_at"], name="raw_azure_s_credent_05aca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawec2snapshot",
            index=models.Index(
                fields=["credential_id", "fetched_at"], name="raw_ec2_sna_credent_1997dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawgcpsnapshot",
            index=models.Index(
                fields=["credential_id", "fetched_at"], name="raw_gcp_sna_credent_584627_idx"
            ),
        ),
    ]
