# Generated by Django 6.0 on 2026-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("instance_type", models.CharField(max_length=50)),
                ("region", models.CharField(default="us-east-1", max_length=50)),
                ("vcpu", models.IntegerField()),
                ("memory_gb", models.DecimalField(decimal_places=2, max_digits=6)),
                ("storage_gb", models.IntegerField(blank=True, null=True)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("crawled_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cloud_services",
                "ordering": ["provider", "price_per_month"],
                "indexes": [
                    models.Index(
                        fields=["provider", "instance_type"],
                        name="cloud_servi_provide_32ad51_idx",
                    ),
                    models.Index(
                        fields=["vcpu", "memory_gb"], name="cloud_servi_vcpu_66d486_idx"
                    ),
                ],
            },
        ),
    ]
