# Generated by Django 6.0 on 2026-02-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        help_text="클라우드 제공자(AWS, GCP, Azure)",
                        max_length=10,
                    ),
                ),
                ("instance_type", models.CharField(help_text="인스턴스 유형", max_length=50)),
                (
                    "region",
                    models.CharField(
                        default="us-east-1", help_text="클라우드 provider 원본 리전", max_length=50
                    ),
                ),
                (
                    "region_normalized",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KR", "South Korea"),
                            ("JP", "Japan"),
                            ("SG", "Singapore"),
                            ("HK", "Hong Kong"),
                            ("IN", "India"),
                            ("AU", "Australia"),
                            ("US_EAST", "US East"),
                            ("US_WEST", "US West"),
                            ("CA", "Canada"),
                        ],
                        help_text="표준화된 리전 코드",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("vcpu", models.IntegerField(help_text="가상환경 컴퓨팅 CPU")),
                (
                    "memory_gb",
                    models.DecimalField(
                        decimal_places=2, help_text="가상환경 컴퓨팅 메모리 용량", max_digits=6
                    ),
                ),
                (
                    "storage_gb",
                    models.IntegerField(
                        blank=True, help_text="가상환경 컴퓨팅 스토리지 용량", null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", help_text="통합코드", max_length=50)),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="클라우드 서비스 시간당 지불 비용",
                        max_digits=10,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("ON_DEMAND", "On Demand"),
                            ("RESERVED", "Reserved / Committed"),
                            ("SPOT", "Spot / Preemptible"),
                        ],
                        help_text="가격모델",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_source",
                    models.CharField(
                        choices=[
                            ("AWS_API", "AWS Price List API"),
                            ("GCP_API", "GCP Cloud Billing API"),
                            ("AZURE_API", "Azure Retail Prices API"),
                        ],
                        help_text="가격 데이터 출처",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                        default="MEDIUM",
                        help_text="가격 신뢰도",
                        max_length=20,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateField(help_text="공식 api를 통해 검증된 마지막 가격정보 갱신시간"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="활성화 상태")),
            ],
            options={
                "db_table": "cloud_services",
                "ordering": ["provider", "price_per_hour"],
                "indexes": [
                    models.Index(
                        fields=["provider", "instance_type"], name="cloud_servi_provide_32ad51_idx"
                    ),
                    models.Index(fields=["vcpu", "memory_gb"], name="cloud_servi_vcpu_66d486_idx"),
                    models.Index(
                        fields=["region_normalized"], name="cloud_servi_region__e63594_idx"
                    ),
                    models.Index(fields=["pricing_model"], name="cloud_servi_pricing_56de81_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "instance_type", "region", "pricing_model"),
                        name="unique_cloud_service",
                    )
                ],
            },
        ),
    ]
