# Generated by Django 6.0 on 2026-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudservice",
            name="memory_gb",
            field=models.DecimalField(
                decimal_places=2, help_text="가상환경 컴퓨팅 메모리 용량", max_digits=10
            ),
        ),
    ]
