# Generated by Django 6.0 on 2026-03-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0002_alter_cloudservice_memory_gb"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cloudservice",
            name="cloud_servi_vcpu_66d486_idx",
        ),
        migrations.RemoveIndex(
            model_name="cloudservice",
            name="cloud_servi_region__e63594_idx",
        ),
        migrations.RemoveIndex(
            model_name="cloudservice",
            name="cloud_servi_pricing_56de81_idx",
        ),
        migrations.AddIndex(
            model_name="cloudservice",
            index=models.Index(
                fields=["vcpu", "memory_gb", "region_normalized", "pricing_model"],
                name="cloud_servi_vcpu_cbad0a_idx",
            ),
        ),
    ]
