# Generated by Django 6.0 on 2026-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0003_optimize_cloudservice_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudservice",
            name="cpu_arch",
            field=models.CharField(
                choices=[("x86_64", "x86_64"), ("arm64", "arm64")],
                default="x86_64",
                help_text="CPU 아키텍처 (x86_64 또는 arm64)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cloudservice",
            name="is_burstable",
            field=models.BooleanField(
                default=False,
                help_text="버스터블 인스턴스 여부 (AWS t시리즈, GCP e2-micro/small, Azure B시리즈)",
            ),
        ),
    ]
