# Generated by Django 6.0 on 2026-02-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("DOWNSIZE", "다운사이징 (스펙 축소)"),
                            ("SWITCH_PROVIDER", "프로바이더 변경 (타사 전환)"),
                            ("SWITCH_PRICING", "가격 모델 변경 (Spot/Reserved)"),
                            ("RIGHTSIZING", "적정 사이징"),
                            ("NO_ACTION", "현행 유지 권장"),
                        ],
                        help_text="추천 유형 (다운사이징, 프로바이더 변경 등)",
                        max_length=20,
                    ),
                ),
                (
                    "original_provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        help_text="원본 프로바이더 (진단 당시 스냅샷)",
                        max_length=10,
                    ),
                ),
                (
                    "original_instance_type",
                    models.CharField(
                        help_text="원본 인스턴스 타입 (진단 당시 스냅샷)", max_length=50
                    ),
                ),
                (
                    "original_monthly_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="원본 월 비용 (진단 당시 스냅샷)", max_digits=10
                    ),
                ),
                (
                    "original_cpu_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="원본 CPU 사용률 (진단 당시 스냅샷)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "expected_monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="추천 서비스 적용 시 예상 월 비용",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="예상 절감액 (original - expected)",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_percentage",
                    models.DecimalField(decimal_places=2, help_text="절감률 (%)", max_digits=5),
                ),
                ("reason", models.TextField(help_text="AI가 생성한 추천 근거 및 설명")),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="추천 신뢰도 점수 (0~100)",
                        max_digits=5,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="추천 우선순위 (1이 가장 높음)"),
                ),
            ],
            options={
                "db_table": "recommendation_items",
                "ordering": ["priority", "-savings_amount"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "분석 중"), ("COMPLETED", "완료"), ("FAILED", "실패")],
                        default="PENDING",
                        help_text="진단 처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "total_current_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="현재 월 비용 (진단 시점 스냅샷)", max_digits=10
                    ),
                ),
                (
                    "total_optimized_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="최적화 후 예상 월 비용", max_digits=10
                    ),
                ),
                (
                    "total_savings",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="총 예상 절감액 (current - optimized)",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="절감률 (%) - save() 시 자동 계산",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("diagnosis_summary", models.TextField(help_text="AI가 생성한 진단 요약 메시지")),
                (
                    "inventory",
                    models.ForeignKey(
                        help_text="진단 대상 인벤토리 (어떤 리소스에 대한 진단인지)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="inventories.userinventory",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["-created_at"],
            },
        ),
    ]
