# Generated by Django 6.0 on 2026-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_current_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_optimized_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_savings", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "savings_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("diagnosis_summary", models.TextField()),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin_provider", models.CharField(default="unknown", max_length=50)),
                ("original_instance_type", models.CharField(max_length=50)),
                (
                    "original_monthly_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "original_cpu_usage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "expected_monthly_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "savings_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "savings_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("reason", models.TextField()),
                ("priority", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "recommendation_items",
                "ordering": ["priority", "-savings_amount"],
            },
        ),
    ]
