# Generated by Django 6.0 on 2026-02-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("costs", "0001_initial"),
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                help_text="추천을 요청한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationitem",
            name="recommendation",
            field=models.ForeignKey(
                help_text="상위 추천 결과",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="recommendations.recommendation",
            ),
        ),
        migrations.AddField(
            model_name="recommendationitem",
            name="recommended_service",
            field=models.ForeignKey(
                blank=True,
                help_text="추천하는 CloudService (삭제되어도 Item 유지)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation_items",
                to="costs.cloudservice",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["user", "status"], name="recommendat_user_id_267621_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["inventory"], name="recommendat_invento_0caa56_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendationitem",
            index=models.Index(fields=["recommendation"], name="recommendat_recomme_24fa1f_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendationitem",
            index=models.Index(
                fields=["recommendation_type"], name="recommendat_recomme_8eaf0b_idx"
            ),
        ),
    ]
