# Generated by Django 6.0 on 2026-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("resource_id", models.CharField(max_length=100)),
                ("instance_type", models.CharField(max_length=50)),
                ("region", models.CharField(default="us-east-1", max_length=50)),
                ("vcpt", models.IntegerField()),
                ("memory_gb", models.DecimalField(decimal_places=2, max_digits=6)),
                ("storage_gb", models.IntegerField(blank=True, null=True)),
                (
                    "cpu_usage_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="평균 CPU 사용률 (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "memory_usage_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="평균 메모리 사용률 (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "current_monthly_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "user_inventories",
                "ordering": ["created_at"],
            },
        ),
    ]
