# Generated by Django 6.0 on 2026-02-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        help_text="클라우드 제공자(AWS, GCP, AZURE)",
                        max_length=10,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(help_text="클라우드 내 고유 리소스 ID", max_length=100),
                ),
                ("instance_type", models.CharField(help_text="인스턴스 유형", max_length=50)),
                ("region", models.CharField(help_text="Provider 원본 리전명", max_length=50)),
                (
                    "region_normalized",
                    models.CharField(
                        choices=[
                            ("KR", "South Korea"),
                            ("JP", "Japan"),
                            ("SG", "Singapore"),
                            ("HK", "Hong Kong"),
                            ("IN", "India"),
                            ("AU", "Australia"),
                            ("US_EAST", "US East"),
                            ("US_WEST", "US West"),
                            ("CA", "Canada"),
                        ],
                        help_text="정규화된 리전명",
                        max_length=10,
                    ),
                ),
                ("vcpu", models.IntegerField(help_text="가상 CPU 코어 수")),
                (
                    "memory_gb",
                    models.DecimalField(
                        decimal_places=2, help_text="메모리 용량(GB)", max_digits=6
                    ),
                ),
                (
                    "storage_gb",
                    models.IntegerField(blank=True, help_text="스토리지 용량(GB)", null=True),
                ),
                (
                    "cpu_usage_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="최근 7일 평균 CPU 사용률 (%) - 과스펙 판단 기준",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "memory_usage_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="최근 7일 평균 메모리 사용률 (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("current_monthly_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", help_text="통화 코드", max_length=3)),
                ("is_active", models.BooleanField(default=True, help_text="활성 상태")),
            ],
            options={
                "db_table": "user_inventories",
                "ordering": ["-created_at"],
            },
        ),
    ]
