# Generated by Django 6.0 on 2026-01-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["user", "is_active"], name="user_invent_user_id_785fa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["provider", "instance_type"],
                name="user_invent_provide_83f501_idx",
            ),
        ),
    ]
