# Generated by Django 6.0 on 2026-02-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="user",
            field=models.ForeignKey(
                help_text="이 리소스를 소유한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(fields=["user", "is_active"], name="user_invent_user_id_785fa2_idx"),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["provider", "instance_type"], name="user_invent_provide_83f501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(fields=["region_normalized"], name="user_invent_region__5bd79b_idx"),
        ),
        migrations.AddConstraint(
            model_name="userinventory",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "resource_id"), name="unique_user_resource"
            ),
        ),
    ]
