# Generated by Django 6.0 on 2026-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="cost_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="Cost Explorer 데이터 기준 시점 (최대 24시간 지연)", null=True
            ),
        ),
    ]
