# Generated by Django 6.0 on 2026-02-08 12:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="소속 회사명", max_length=100, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="연락처", max_length=20, null=True),
                ),
                (
                    "default_provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        default="AWS",
                        help_text="기본 클라우드 제공자(대시보드 기본값)",
                        max_length=10,
                    ),
                ),
                (
                    "default_region",
                    models.CharField(
                        choices=[
                            ("KR", "South Korea"),
                            ("JP", "Japan"),
                            ("SG", "Singapore"),
                            ("HK", "Hong Kong"),
                            ("IN", "India"),
                            ("AU", "Australia"),
                            ("US_EAST", "US East"),
                            ("US_WEST", "US West"),
                            ("CA", "Canada"),
                        ],
                        default="KR",
                        help_text="기본 리전(대시보드 기본값)",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        default="USD", help_text="기본 통화(USD, KRW 등)", max_length=3
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, help_text="프리미엄 사용자 여부"),
                ),
                (
                    "subscription_ends_at",
                    models.DateField(blank=True, help_text="구독 만료일", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CloudCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                        ],
                        help_text="클라우드 제공자(AWS, GCP, Azure)",
                        max_length=10,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("ACCESS_KEY", "Access Key(AWS)"),
                            ("SERVICE_ACCOUNT", "Service Account(GCP)"),
                            ("SERVICE_PRINCIPAL", "Service Principal(Azure)"),
                        ],
                        help_text="인증 방식",
                        max_length=20,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, help_text="사용자 지정 별칭", max_length=50),
                ),
                (
                    "aws_access_key_id",
                    models.CharField(
                        blank=True,
                        help_text="AWS Access Key ID (암호화 필요)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "aws_secret_access_key",
                    models.CharField(
                        blank=True,
                        help_text="AWS Secret Access Key (암호화 필요)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "aws_default_region",
                    models.CharField(
                        blank=True,
                        help_text="AWS 기본 리전 (예: ap-northeast-2)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gcp_project_id",
                    models.CharField(
                        blank=True, help_text="GCP Project ID", max_length=100, null=True
                    ),
                ),
                (
                    "gcp_service_account_json",
                    models.TextField(
                        blank=True, help_text="GCP Service Account JSON (암호화 필요)", null=True
                    ),
                ),
                (
                    "azure_tenant_id",
                    models.CharField(
                        blank=True, help_text="Azure Tenant ID", max_length=100, null=True
                    ),
                ),
                (
                    "azure_client_id",
                    models.CharField(
                        blank=True, help_text="Azure Client ID", max_length=100, null=True
                    ),
                ),
                (
                    "azure_client_secret",
                    models.CharField(
                        blank=True,
                        help_text="Azure Client Secret (암호화 필요)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "azure_subscription_id",
                    models.CharField(
                        blank=True, help_text="Azure Subscription ID", max_length=100, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성 상태 (False면 연동 해제)"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="인증 정보 검증 완료 여부"),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(blank=True, help_text="마지막 검증 시간", null=True),
                ),
                (
                    "verification_error",
                    models.TextField(blank=True, help_text="검증 실패 시 에러 메시지", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="연동된 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "클라우드 인증 정보",
                "verbose_name_plural": "클라우드 인증 정보 목록",
                "db_table": "cloud_credentials",
                "indexes": [
                    models.Index(
                        fields=["user", "provider"], name="cloud_crede_user_id_6dffae_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="cloud_crede_user_id_e2d343_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider", "nickname"),
                        name="unique_user_provider_nickname",
                    )
                ],
            },
        ),
    ]
