# Generated by Django 6.0 on 2026-03-06 04:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudcredential",
            name="aws_access_key_id",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="AWS Access Key ID (암호화 필요)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cloudcredential",
            name="aws_secret_access_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="AWS Secret Access Key (암호화 필요)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cloudcredential",
            name="azure_client_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Azure Client Secret (암호화 필요)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cloudcredential",
            name="gcp_service_account_json",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="GCP Service Account JSON (암호화 필요)", null=True
            ),
        ),
    ]
