# Generated by Django 6.0 on 2026-01-03 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_recommend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recommendationitem',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='created_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='snapshot_instance_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='snapshot_price_per_hour',
            field=models.FloatField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='snapshot_provider',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='snapshot_region',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendationitem',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_items', to='solution_recommend.recommendation'),
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendations',
        ),
    ]
