# Generated by Django 6.0 on 2026-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_recommend', '0002_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationitem',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='validated',
            field=models.FloatField(default=False),
        ),
    ]
